### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Nachh** [posterpole/vscode#1]
Hi, I just wanted to thank you for your contribution. I really like the colours and they feel very comfortable in my eyes. 

On the other hand I wanted to suggest from the most sincere humility that you develop a little the colour scheme to expand it, that is, I see potential similar to Nord, Catppuccin, Rose pine, Kanagawa, etc ... which are schemes that have transcended and are also used in the terminal, linux themes, TUI apps, etc ... through contributions from the community.

Best regards !

**Comment by ilof2** [comment]
Thank you for using my theme, I am doing my best to expand it everywhere :) Without community support, built-in integrations with non-extendable applications can appear with a huge delay.
For now, you can use this theme in the Alacritty and the nvim. Shortly will be added Wezterm, Kitty, and iTerm support. Ghostty will be supported after the release (beta invite issues)
If you have any issues with wrong highlighting feel free to create issues on github.

Thanks for the review!
Best regards
